In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_excel(r'D:\VS Code\NATPAC\dataset\agro-products.xlsx')

In [23]:
print(df.dtypes)

Sail Date.    object
QTY.(KGS)      int64
dtype: object

In [24]:
df['Sail Date.']=pd.to_datetime(df['Sail Date.'])

In [25]:
df.head(10)

  Sail Date.  QTY.(KGS)
0 2018-01-01      13135
1 2018-01-01      15876
2 2018-01-01      71366
3 2018-01-01      14000
4 2018-01-01      24000
5 2018-01-01      24000
6 2018-01-01      16000
7 2018-01-01      15876
8 2018-01-01       1014
9 2018-01-01      20124

In [26]:
df.sort_values(by='Sail Date.', inplace=True)

In [27]:
#df = df.groupby('Sail Date.')['QTY.(KGS)'].sum().reset_index()

In [28]:
#aggregate quantities for each date
df.head(10)

   Sail Date.  QTY.(KGS)
0  2018-01-01      13135
16 2018-01-01      24000
15 2018-01-01      19200
14 2018-01-01      15918
12 2018-01-01       3100
11 2018-01-01      29000
10 2018-01-01      15000
9  2018-01-01      20124
13 2018-01-01      15876
7  2018-01-01      15876

In [29]:
duplicates = df.groupby(['Sail Date.', 'QTY.(KGS)']).size().reset_index(name='Count')

duplicates = duplicates[duplicates['Count'] > 1]

for date, group in duplicates.groupby('Sail Date.'):
    print("Duplicates for Date:", date.strftime('%Y-%m-%d'))
    for index, row in group.iterrows():
        print("Quantity:", row['QTY.(KGS)'], "- Duplicated", row['Count'], "times")
    print()

Duplicates for Date: 2018-01-01
Quantity: 15876 - Duplicated 3 times
Quantity: 24000 - Duplicated 3 times

Duplicates for Date: 2018-01-04
Quantity: 24000 - Duplicated 2 times
Quantity: 48000 - Duplicated 3 times

Duplicates for Date: 2018-01-05
Quantity: 11000 - Duplicated 2 times
Quantity: 15000 - Duplicated 5 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 27800 - Duplicated 2 times

Duplicates for Date: 2018-01-06
Quantity: 12500 - Duplicated 2 times
Quantity: 15876 - Duplicated 3 times
Quantity: 18000 - Duplicated 3 times
Quantity: 19200 - Duplicated 4 times
Quantity: 19432 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times

Duplicates for Date: 2018-01-07
Quantity: 13000 - Duplicated 2 times
Quantity: 15000 - Duplicated 3 times
Quantity: 15876 - Duplicated 3 times
Quantity: 18000 - Duplicated 3 times
Quantity: 19200 - Duplicated 3 times
Quantity: 24000 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times
Quantity: 76800 - Duplicated 2 times

Duplicates for Date: 2018-01-08
Quantity: 15000 - Duplicated 6 times
Quantity: 24000 - Duplicated 5 times
Quantity: 28000 - Duplicated 2 times
Quantity: 48000 - Duplicated 2 times

Duplicates for Date: 2018-01-09
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-01-10
Quantity: 15000 - Duplicated 3 times
Quantity: 15876 - Duplicated 2 times
Quantity: 18000 - Duplicated 2 times
Quantity: 24000 - Duplicated 8 times
Quantity: 25000 - Duplicated 3 times
Quantity: 27500 - Duplicated 3 times
Quantity: 48000 - Duplicated 2 times

Duplicates for Date: 2018-01-14
Quantity: 11000 - Duplicated 2 times
Quantity: 15000 - Duplicated 3 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-01-15
Quantity: 15000 - Duplicated 7 times
Quantity: 15876 - Duplicated 2 times
Quantity: 16200 - Duplicated 2 times
Quantity: 19200 - Duplicated 3 times
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 3 times
Quantity: 28000 - Duplicated 2 times
Quantity: 30000 - Duplicated 2 times
Quantity: 30876 - Duplicated 2 times
Quantity: 49000 - Duplicated 2 times

Duplicates for Date: 2018-01-17
Quantity: 9000 - Duplicated 2 times
Quantity: 10000 - Duplicated 2 times
Quantity: 15876 - Duplicated 6 times
Quantity: 31752 - Duplicated 3 times

Duplicates for Date: 2018-01-18
Quantity: 15000 - Duplicated 5 times
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-01-19
Quantity: 8000 - Duplicated 3 times
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 3 times
Quantity: 22000 - Duplicated 2 times
Quantity: 23500 - Duplicated 2 times

Duplicates for Date: 2018-01-22
Quantity: 10000 - Duplicated 3 times
Quantity: 15876 - Duplicated 5 times
Quantity: 16329 - Duplicated 2 times
Quantity: 18000 - Duplicated 2 times
Quantity: 21000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 3 times
Quantity: 26000 - Duplicated 2 times
Quantity: 30000 - Duplicated 3 times

Duplicates for Date: 2018-01-26
Quantity: 15876 - Duplicated 3 times
Quantity: 25000 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times

Duplicates for Date: 2018-01-27
Quantity: 12000 - Duplicated 2 times
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 3 times
Quantity: 18000 - Duplicated 2 times

Duplicates for Date: 2018-01-28
Quantity: 8000 - Duplicated 2 times
Quantity: 15000 - Duplicated 4 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-01-29
Quantity: 15000 - Duplicated 4 times
Quantity: 16000 - Duplicated 2 times
Quantity: 27500 - Duplicated 3 times

Duplicates for Date: 2018-01-30
Quantity: 8000 - Duplicated 2 times
Quantity: 15876 - Duplicated 2 times

Duplicates for Date: 2018-02-01
Quantity: 15000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 30000 - Duplicated 3 times

Duplicates for Date: 2018-02-02
Quantity: 13000 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 21000 - Duplicated 2 times
Quantity: 22000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 26000 - Duplicated 2 times

Duplicates for Date: 2018-02-03
Quantity: 8000 - Duplicated 2 times
Quantity: 11000 - Duplicated 2 times
Quantity: 12000 - Duplicated 2 times
Quantity: 13000 - Duplicated 2 times
Quantity: 15876 - Duplicated 4 times
Quantity: 18000 - Duplicated 3 times
Quantity: 19200 - Duplicated 3 times

Duplicates for Date: 2018-02-04
Quantity: 15000 - Duplicated 2 times
Quantity: 24000 - Duplicated 4 times
Quantity: 25000 - Duplicated 3 times
Quantity: 26000 - Duplicated 2 times
Quantity: 27500 - Duplicated 3 times

Duplicates for Date: 2018-02-06
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-02-07
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times

Duplicates for Date: 2018-02-10
Quantity: 15876 - Duplicated 4 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-02-11
Quantity: 9000 - Duplicated 2 times
Quantity: 15876 - Duplicated 3 times

Duplicates for Date: 2018-02-12
Quantity: 15000 - Duplicated 5 times

Duplicates for Date: 2018-02-13
Quantity: 12000 - Duplicated 2 times
Quantity: 12500 - Duplicated 3 times
Quantity: 15876 - Duplicated 8 times
Quantity: 16000 - Duplicated 2 times
Quantity: 19200 - Duplicated 4 times
Quantity: 20000 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 2 times
Quantity: 26000 - Duplicated 2 times
Quantity: 28000 - Duplicated 3 times
Quantity: 30876 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times

Duplicates for Date: 2018-02-16
Quantity: 8000 - Duplicated 2 times
Quantity: 15876 - Duplicated 5 times
Quantity: 38400 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-02-18
Quantity: 15000 - Duplicated 6 times
Quantity: 24000 - Duplicated 6 times
Quantity: 48000 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-02-19
Quantity: 7500 - Duplicated 2 times
Quantity: 15000 - Duplicated 5 times
Quantity: 15876 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 3 times

Duplicates for Date: 2018-02-23
Quantity: 15876 - Duplicated 4 times

Duplicates for Date: 2018-02-24
Quantity: 13500 - Duplicated 2 times
Quantity: 15000 - Duplicated 9 times
Quantity: 15876 - Duplicated 3 times
Quantity: 18143 - Duplicated 2 times
Quantity: 25000 - Duplicated 5 times
Quantity: 27300 - Duplicated 2 times
Quantity: 37200 - Duplicated 2 times
Quantity: 40000 - Duplicated 2 times

Duplicates for Date: 2018-02-28
Quantity: 15000 - Duplicated 6 times
Quantity: 15876 - Duplicated 3 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 2 times
Quantity: 26000 - Duplicated 2 times
Quantity: 48000 - Duplicated 2 times

Duplicates for Date: 2018-03-01
Quantity: 8000 - Duplicated 2 times
Quantity: 15876 - Duplicated 6 times
Quantity: 19200 - Duplicated 3 times
Quantity: 38400 - Duplicated 2 times

Duplicates for Date: 2018-03-04
Quantity: 13000 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times

Duplicates for Date: 2018-03-07
Quantity: 12000 - Duplicated 2 times
Quantity: 15000 - Duplicated 6 times
Quantity: 19200 - Duplicated 2 times
Quantity: 27000 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-03-09
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 3 times
Quantity: 27000 - Duplicated 2 times
Quantity: 28000 - Duplicated 2 times

Duplicates for Date: 2018-03-10
Quantity: 25740 - Duplicated 2 times

Duplicates for Date: 2018-03-11
Quantity: 15000 - Duplicated 2 times

Duplicates for Date: 2018-03-12
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-03-13
Quantity: 15000 - Duplicated 5 times
Quantity: 15876 - Duplicated 4 times
Quantity: 18000 - Duplicated 2 times
Quantity: 25000 - Duplicated 2 times
Quantity: 26500 - Duplicated 3 times

Duplicates for Date: 2018-03-16
Quantity: 19200 - Duplicated 3 times
Quantity: 19500 - Duplicated 2 times
Quantity: 58400 - Duplicated 2 times

Duplicates for Date: 2018-03-19
Quantity: 12500 - Duplicated 2 times
Quantity: 15000 - Duplicated 6 times
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 25000 - Duplicated 2 times
Quantity: 27300 - Duplicated 3 times
Quantity: 30000 - Duplicated 2 times

Duplicates for Date: 2018-03-20
Quantity: 500 - Duplicated 2 times
Quantity: 15000 - Duplicated 3 times
Quantity: 15876 - Duplicated 5 times
Quantity: 20000 - Duplicated 2 times
Quantity: 24000 - Duplicated 5 times
Quantity: 63000 - Duplicated 2 times

Duplicates for Date: 2018-03-21
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-03-23
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-03-24
Quantity: 15876 - Duplicated 2 times

Duplicates for Date: 2018-03-26
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times

Duplicates for Date: 2018-03-27
Quantity: 14000 - Duplicated 2 times
Quantity: 15000 - Duplicated 5 times
Quantity: 15876 - Duplicated 5 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 3 times
Quantity: 27000 - Duplicated 2 times
Quantity: 46000 - Duplicated 2 times

Duplicates for Date: 2018-03-30
Quantity: 15000 - Duplicated 3 times
Quantity: 15876 - Duplicated 5 times
Quantity: 19200 - Duplicated 2 times
Quantity: 23000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-03-31
Quantity: 28200 - Duplicated 2 times

Duplicates for Date: 2018-04-02
Quantity: 15000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 27600 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times

Duplicates for Date: 2018-04-03
Quantity: 15000 - Duplicated 3 times

Duplicates for Date: 2018-04-05
Quantity: 15876 - Duplicated 5 times
Quantity: 38400 - Duplicated 2 times

Duplicates for Date: 2018-04-06
Quantity: 15000 - Duplicated 8 times
Quantity: 27000 - Duplicated 2 times
Quantity: 30000 - Duplicated 2 times
Quantity: 48000 - Duplicated 2 times

Duplicates for Date: 2018-04-08
Quantity: 24000 - Duplicated 3 times

Duplicates for Date: 2018-04-11
Quantity: 15876 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-04-12
Quantity: 8200 - Duplicated 2 times
Quantity: 12000 - Duplicated 2 times
Quantity: 12500 - Duplicated 2 times
Quantity: 15000 - Duplicated 7 times
Quantity: 15876 - Duplicated 5 times
Quantity: 24000 - Duplicated 4 times
Quantity: 31752 - Duplicated 3 times
Quantity: 48000 - Duplicated 3 times
Quantity: 72000 - Duplicated 2 times

Duplicates for Date: 2018-04-13
Quantity: 15000 - Duplicated 2 times
Quantity: 18000 - Duplicated 3 times
Quantity: 50000 - Duplicated 2 times

Duplicates for Date: 2018-04-16
Quantity: 15000 - Duplicated 3 times
Quantity: 15876 - Duplicated 2 times
Quantity: 27500 - Duplicated 2 times
Quantity: 28000 - Duplicated 4 times

Duplicates for Date: 2018-04-17
Quantity: 15000 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-04-20
Quantity: 15876 - Duplicated 4 times
Quantity: 19200 - Duplicated 2 times
Quantity: 21000 - Duplicated 2 times

Duplicates for Date: 2018-04-22
Quantity: 15000 - Duplicated 2 times
Quantity: 25000 - Duplicated 4 times

Duplicates for Date: 2018-04-23
Quantity: 15000 - Duplicated 4 times
Quantity: 24000 - Duplicated 5 times
Quantity: 27000 - Duplicated 2 times
Quantity: 28000 - Duplicated 2 times
Quantity: 48000 - Duplicated 2 times

Duplicates for Date: 2018-04-24
Quantity: 15876 - Duplicated 2 times
Quantity: 18000 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-04-28
Quantity: 27500 - Duplicated 2 times

Duplicates for Date: 2018-04-29
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 3 times

Duplicates for Date: 2018-04-30
Quantity: 15000 - Duplicated 5 times
Quantity: 24000 - Duplicated 5 times

Duplicates for Date: 2018-05-01
Quantity: 8000 - Duplicated 2 times
Quantity: 12500 - Duplicated 2 times
Quantity: 15876 - Duplicated 4 times
Quantity: 19200 - Duplicated 2 times

Duplicates for Date: 2018-05-03
Quantity: 15876 - Duplicated 3 times
Quantity: 19200 - Duplicated 3 times

Duplicates for Date: 2018-05-06
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times

Duplicates for Date: 2018-05-08
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-05-09
Quantity: 18000 - Duplicated 3 times
Quantity: 23000 - Duplicated 2 times

Duplicates for Date: 2018-05-10
Quantity: 11000 - Duplicated 2 times

Duplicates for Date: 2018-05-11
Quantity: 15000 - Duplicated 3 times
Quantity: 17000 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times
Quantity: 27000 - Duplicated 2 times
Quantity: 28000 - Duplicated 2 times
Quantity: 48000 - Duplicated 3 times

Duplicates for Date: 2018-05-14
Quantity: 15000 - Duplicated 6 times
Quantity: 24000 - Duplicated 5 times
Quantity: 25000 - Duplicated 2 times
Quantity: 96000 - Duplicated 3 times

Duplicates for Date: 2018-05-15
Quantity: 15876 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 4 times

Duplicates for Date: 2018-05-19
Quantity: 15876 - Duplicated 5 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 172800 - Duplicated 2 times

Duplicates for Date: 2018-05-21
Quantity: 15000 - Duplicated 6 times
Quantity: 15876 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 72000 - Duplicated 2 times

Duplicates for Date: 2018-05-22
Quantity: 12500 - Duplicated 2 times
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 5 times
Quantity: 19200 - Duplicated 3 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-05-23
Quantity: 15000 - Duplicated 3 times

Duplicates for Date: 2018-05-26
Quantity: 14000 - Duplicated 2 times
Quantity: 15876 - Duplicated 2 times
Quantity: 18000 - Duplicated 3 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 4 times
Quantity: 25000 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-05-27
Quantity: 11000 - Duplicated 2 times
Quantity: 15000 - Duplicated 9 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 6 times
Quantity: 28500 - Duplicated 2 times
Quantity: 53000 - Duplicated 2 times
Quantity: 79500 - Duplicated 2 times

Duplicates for Date: 2018-05-30
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 3 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24600 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times

Duplicates for Date: 2018-05-31
Quantity: 15000 - Duplicated 2 times

Duplicates for Date: 2018-06-02
Quantity: 12500 - Duplicated 2 times
Quantity: 15000 - Duplicated 5 times
Quantity: 15876 - Duplicated 2 times
Quantity: 18000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 25000 - Duplicated 4 times
Quantity: 38400 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-06-03
Quantity: 12500 - Duplicated 2 times
Quantity: 15000 - Duplicated 8 times
Quantity: 15876 - Duplicated 3 times
Quantity: 16000 - Duplicated 2 times
Quantity: 19200 - Duplicated 3 times
Quantity: 22000 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 4 times
Quantity: 27500 - Duplicated 2 times
Quantity: 27900 - Duplicated 2 times
Quantity: 30000 - Duplicated 2 times

Duplicates for Date: 2018-06-04
Quantity: 8000 - Duplicated 2 times
Quantity: 11000 - Duplicated 2 times
Quantity: 15876 - Duplicated 4 times
Quantity: 30000 - Duplicated 2 times

Duplicates for Date: 2018-06-07
Quantity: 15000 - Duplicated 3 times
Quantity: 15876 - Duplicated 6 times
Quantity: 18000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times
Quantity: 38400 - Duplicated 2 times

Duplicates for Date: 2018-06-08
Quantity: 8000 - Duplicated 3 times
Quantity: 13500 - Duplicated 2 times
Quantity: 15000 - Duplicated 6 times
Quantity: 15876 - Duplicated 2 times
Quantity: 24000 - Duplicated 5 times
Quantity: 27000 - Duplicated 3 times
Quantity: 28000 - Duplicated 5 times
Quantity: 30000 - Duplicated 2 times
Quantity: 48000 - Duplicated 3 times
Quantity: 96000 - Duplicated 2 times

Duplicates for Date: 2018-06-10
Quantity: 15876 - Duplicated 2 times
Quantity: 28000 - Duplicated 3 times

Duplicates for Date: 2018-06-11
Quantity: 15000 - Duplicated 7 times
Quantity: 15876 - Duplicated 7 times
Quantity: 18000 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 4 times

Duplicates for Date: 2018-06-13
Quantity: 19200 - Duplicated 4 times

Duplicates for Date: 2018-06-15
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 3 times

Duplicates for Date: 2018-06-18
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-06-19
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 5 times
Quantity: 19200 - Duplicated 3 times
Quantity: 22000 - Duplicated 4 times
Quantity: 24000 - Duplicated 3 times
Quantity: 31752 - Duplicated 2 times
Quantity: 48000 - Duplicated 2 times
Quantity: 96000 - Duplicated 3 times

Duplicates for Date: 2018-06-22
Quantity: 15876 - Duplicated 5 times
Quantity: 18000 - Duplicated 2 times
Quantity: 31752 - Duplicated 2 times
Quantity: 57600 - Duplicated 2 times

Duplicates for Date: 2018-06-23
Quantity: 24000 - Duplicated 4 times

Duplicates for Date: 2018-06-24
Quantity: 15876 - Duplicated 3 times

Duplicates for Date: 2018-06-25
Quantity: 15000 - Duplicated 3 times
Quantity: 24000 - Duplicated 2 times
Quantity: 50000 - Duplicated 2 times

Duplicates for Date: 2018-06-26
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 4 times
Quantity: 24000 - Duplicated 5 times

Duplicates for Date: 2018-06-27
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-06-30
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-07-02
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-07-03
Quantity: 15000 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times

Duplicates for Date: 2018-07-04
Quantity: 15000 - Duplicated 3 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 2 times

Duplicates for Date: 2018-07-05
Quantity: 15000 - Duplicated 7 times
Quantity: 15876 - Duplicated 2 times
Quantity: 20000 - Duplicated 3 times
Quantity: 24000 - Duplicated 4 times
Quantity: 30000 - Duplicated 2 times

Duplicates for Date: 2018-07-06
Quantity: 15000 - Duplicated 2 times
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-07-08
Quantity: 15876 - Duplicated 7 times
Quantity: 16000 - Duplicated 2 times
Quantity: 19200 - Duplicated 2 times
Quantity: 24000 - Duplicated 3 times
Quantity: 25000 - Duplicated 2 times
Quantity: 30876 - Duplicated 2 times

Duplicates for Date: 2018-07-09
Quantity: 15000 - Duplicated 4 times
Quantity: 15876 - Duplicated 2 times
Quantity: 24000 - Duplicated 4 times
Quantity: 50000 - Duplicated 2 times

Duplicates for Date: 2018-07-10
Quantity: 15876 - Duplicated 2 times
Quantity: 22000 - Duplicated 2 times

Duplicates for Date: 2018-07-11
Quantity: 24000 - Duplicated 2 times

Duplicates for Date: 2018-07-12
Quantity: 12140 - Duplicated 2 times
Quantity: 15000 - Duplicated 2 times
Quantity: 15876 - Duplicated 6 times
Quantity: 18000 - Duplicated 3 times
Quantity: 25000 - Duplicated 3 times

Duplicates for Date: 2018-07-14
Quantity: 15876 - Duplicated 3 times

Duplicates for Date: 2018-07-15
Quantity: 12500 - Duplicated 3 times
Quantity: 15876 - Duplicated 6 times
Quantity: 24000 - Duplicated 2 times


In [30]:
cleaned_df = df.drop_duplicates(subset=['Sail Date.', 'QTY.(KGS)'])

summed_data = cleaned_df.groupby('Sail Date.')['QTY.(KGS)'].sum().reset_index()

summed_data.to_csv('cleaned_agro_2018.csv', index=False)